Exercise modified code
Prerendered/online_classroom_back pull request #8
Opened 2023-09-01 07:31 UTC by EmmanuelBuruvuru

2023-09-01 07:36 UTC, EmmanuelBuruvuru commented
Pull request for the exercise modification code

2023-09-04 17:01 UTC, Prerendered approved these changes

2023-09-04 17:01 UTC, Prerendered commented
push into sprint 2 not main

2023-09-04 17:01 UTC, Prerendered requested changes
push into sprint 2 first, not main

2023-09-06 17:18 UTC, closed without merging